# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analyze_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_analyzeWindow(object):
    def setupUi(self, analyzeWindow):
        analyzeWindow.setObjectName("analyzeWindow")
        analyzeWindow.resize(1042, 632)
        analyzeWindow.setMinimumSize(QtCore.QSize(1042, 632))
        analyzeWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        analyzeWindow.setAutoFillBackground(False)
        self.left = QtWidgets.QWidget(analyzeWindow)
        self.left.setGeometry(QtCore.QRect(20, 20, 211, 591))
        self.left.setObjectName("left")
        self.treeView = QtWidgets.QTreeView(self.left)
        self.treeView.setGeometry(QtCore.QRect(10, 320, 191, 261))
        self.treeView.setObjectName("treeView")
        self.engage = QtWidgets.QPushButton(self.left)
        self.engage.setGeometry(QtCore.QRect(10, 260, 191, 41))
        self.engage.setObjectName("engage")
        self.textEdit = QtWidgets.QTextEdit(self.left)
        self.textEdit.setGeometry(QtCore.QRect(10, 30, 191, 121))
        self.textEdit.setObjectName("textEdit")
        self.add = QtWidgets.QRadioButton(self.left)
        self.add.setGeometry(QtCore.QRect(20, 166, 117, 21))
        self.add.setObjectName("add")
        self.buttonGroup = QtWidgets.QButtonGroup(analyzeWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.add)
        self.edit = QtWidgets.QRadioButton(self.left)
        self.edit.setGeometry(QtCore.QRect(20, 196, 117, 21))
        self.edit.setObjectName("edit")
        self.buttonGroup.addButton(self.edit)
        self.dele = QtWidgets.QRadioButton(self.left)
        self.dele.setGeometry(QtCore.QRect(20, 226, 117, 21))
        self.dele.setObjectName("del")
        self.buttonGroup.addButton(self.dele)
        self.right = QtWidgets.QWidget(analyzeWindow)
        self.right.setGeometry(QtCore.QRect(240, 20, 781, 591))
        self.right.setObjectName("right")
        self.tabWidget = QtWidgets.QTabWidget(self.right)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 781, 591))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(0, 0, 781, 561))
        self.widget.setObjectName("widget")
        self.textEdit_2 = QtWidgets.QTextEdit(self.widget)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 10, 761, 541))
        self.textEdit_2.setObjectName("textEdit_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(analyzeWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(analyzeWindow)

    def retranslateUi(self, analyzeWindow):
        _translate = QtCore.QCoreApplication.translate
        analyzeWindow.setWindowTitle(_translate("analyzeWindow", "Form"))
        self.engage.setText(_translate("analyzeWindow", "PushButton"))
        self.add.setText(_translate("analyzeWindow", "ADD"))
        self.edit.setText(_translate("analyzeWindow", "EDIT"))
        self.dele.setText(_translate("analyzeWindow", "DELETE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("analyzeWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("analyzeWindow", "Tab 2"))
